CREATE OR REPLACE TRIGGER sup_Adherent
BEFORE DELETE ON Adherent
FOR EACH ROW
DECLARE 
BEGIN
DELETE FROM RESERVATION WHERE RESERVATION.noAdh=:OLD.noAdh;
DELETE FROM EMPRUNT WHERE EMPRUNT.noAdh=:OLD.noAdh;
DBMS_OUTPUT.PUT_LINE('Supprission faite par succés');
END sup_Adherent;